# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'v59' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for v59
  
  pod 'BaiduMapKit', '4.2.0'
  pod 'BMKLocationKit', '1.3.0.2'
  pod 'OpenSSL-Universal'

  target 'v59Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

